### PR TITLE
build with kahip

### LINKED ISSUE #7: add KaHIP
[KaHIP](https://kahip.github.io) is an optional dependency, but not yet on conda-forge.

### PR DESCRIPTION
**Pull request by minrk**
closes #7

### CODE REVIEW

**Comment by minrk** [comment]
@conda-forge-admin please rerender

**Comment by thisch** [comment]
I guess the reason why this hasn't yet been merged is that some build jobs failed.

One issue e.g. is a package installation issue

```
The reported errors are:
- Encountered problems while solving:
-   - package kahip-python-3.14-py310hf89145f_2 requires kahip 3.14 h95d9719_2, but none of the providers can be installed
```

in https://app.travis-ci.com/github/conda-forge/fenics-dolfinx-feedstock/jobs/594046827

Do you maybe know why this happened?

**Comment by minrk** [comment]
Almost everything is solved, but I can't quite get kahip because:

1. fixed kahip builds use mpich 4.1
2. default hdf5 1.12 builds pin mpich 4.0.*, so reject 4.1
3. hdf5 1.14 fixes mpich pin, but has fundamentally broken cmake files (#36, https://github.com/HDFGroup/hdf5/issues/2422)
4. hdf5 1.14.1 fixes cmake, but is stalling because it's actually broken on mpich 4.1 due to new error checking (https://github.com/pmodels/mpich/pull/6186, https://github.com/conda-forge/hdf5-feedstock/pull/202)

**Comment by minrk** [comment]
Huzzah!

**Pull request merged**
